GET http://localhost:6969/

###

GET http://localhost:6969/api/characters


###

GET http://localhost:6969/api/filtered-characters/Spock


###

POST http://localhost:6969/api/characters/
Content-Type: application/json

{
    "id" : null,
    "name": "Spock",
    "rank": "Master cheif petty officer",
    "img": "placeholder.jpg"
}

###

DELETE http://localhost:6969/api/characters/knesgqrl
### 

PUT http://localhost:6969/api/characters/knesgqrl
Content-Type: application/json

{
    "name": "losdsdl",
    "rank": "First Officer",
    "img": "placeholder.jpg"
    
}

